language: python
python:
  - "3.6"

services:
  - docker

install:
  - apt-get pylint

# command to install dependencies
before_install:
  - docker-compose build

after_install:
  - pylint AngleDetection.py
