language: python
python:
  - "3.6"

services:
  - docker

# command to install dependencies
before_install:
  - sudo apt-get install pylint
  - docker-compose build

after_install:
  - pylint AngleDetection.py
